#!/bin/bash
VOLUME="vol:$(amixer sget Master | awk -F"[][]" '/dB/ { print $2" "$6}')"
BATTERY="bat:$(cat /sys/class/power_supply/BAT0/capacity)%" 
WEATHER=$(cat ~/.config/dwm/barweather)
DATE=$(date '+%A-%d %I:%M')
xsetroot -name " | $VOLUME | $BATTERY | $WEATHER | $DATE"
exit

