#!/bin/sh
DMENU_CMD="dmenu -i -fn Terminus:size=11 -nb #222222 -nf #bbbbbb -sb #005577 -sf #eeeeee"
CHOICES="DuckDuckGo
URL
YouTube"

CHOICE=$(printf "$CHOICES" | $DMENU_CMD -p "Go where?")
SWALLOW=

case $CHOICE in
	DuckDuckGo ) printf '' | $DMENU_CMD -p 'Search:' | sed 's|^|https://duckduckgo.com/?q=|' | sed 's/ /%20/g' | xargs $SWALLOW chromium > /dev/null ;;
	URL) printf '' | $DMENU_CMD -p 'Enter URL(s):' | xargs $SWALLOW chromium > /dev/null ;;
	YouTube) printf '' | $DMENU_CMD -p 'Search:' | sed 's|^|https://youtube.com/results?search_query=|' | sed 's/ /%20/g' | xargs $SWALLOW chromium > /dev/null ;;
esac
